version: 2.1

latest: &latest
  pattern: "^1.16.*$"

tags:
  &tags [
    1.16.1-erlang-26.2.2-alpine-3.19.1,
    1.15.7-erlang-26.2.2-alpine-3.19.1,
    1.14.5-erlang-25.3.2.9-alpine-3.19.1,
    1.13.4-erlang-24.3.4-alpine-3.15.3,
    1.12.3-erlang-24.3.4-alpine-3.15.3,
    1.11.4-erlang-23.3.4.13-alpine-3.15.3,
  ]

jobs:
  check-license:
    docker:
      - image: fsfe/reuse:latest
    steps:
      - checkout
      - run: reuse lint

  build-test:
    parameters:
      tag:
        type: string
    docker:
      - image: hexpm/elixir:<< parameters.tag >>
    working_directory: ~/repo
    environment:
      LC_ALL: C.UTF-8
    steps:
      - run:
          name: Install system dependencies
          command: apk add --no-cache build-base procps
      - checkout
      - run:
          name: Install hex and rebar
          command: |
            mix local.hex --force
            mix local.rebar --force
      - restore_cache:
          keys:
            - v1-mix-cache-<< parameters.tag >>-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix test --exclude cgroup
      - when:
          condition:
            matches: { <<: *latest, value: << parameters.tag >> }
          steps:
            - run: mix format --check-formatted
            - run: mix deps.unlock --check-unused
            - run: mix docs
            - run: mix hex.build
            - run: mix credo -a --strict
            - run: mix dialyzer
      - save_cache:
          key: v1-mix-cache-<< parameters.tag >>-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps

workflows:
  checks:
    jobs:
      - check-license
      - build-test:
          name: << matrix.tag >>
          matrix:
            parameters:
              tag: *tags
